<?php

namespace Database\Seeders;

use App\Models\SheetData;
use App\Support\SheetDataSchedule;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class SheetDataSeeder extends Seeder
{
    public function run(): void
    {
        SheetData::where('id', '>', 0)->delete();

        $routes = $this->getRoutes();
        $totalRows = 0;

        foreach ($routes as $route) {
            $dateFrom = Carbon::parse($route['date_from']);
            $dateTo = Carbon::parse($route['date_to']);
            $deliveryWeekdays = SheetDataSchedule::normalizeWeekdays($route['delivery_weekdays']);
            $shipmentWeekdays = SheetDataSchedule::normalizeWeekdays($route['shipment_weekdays']);
            $minTransit = $route['min_transit_days'];

            $rows = [];
            $current = $dateFrom->copy()->startOfDay();

            while ($current->lte($dateTo)) {
                if (in_array($current->dayOfWeek, $deliveryWeekdays, true)) {
                    $shipmentDate = $this->resolveShipmentWithTransit($current, $shipmentWeekdays, $minTransit);

                    if ($shipmentDate !== null) {
                        $rows[] = [
                            'wh' => $route['wh'],
                            'wh_address' => $route['wh_address'],
                            'map' => $route['map'],
                            'distributor' => $route['distributor'],
                            'distributor_center' => $route['distributor_center'],
                            'distributor_address' => $route['distributor_address'],
                            'distributor_center_delivery_date' => $current->format('Y-m-d'),
                            'delivery_weekdays_config' => json_encode($deliveryWeekdays, JSON_UNESCAPED_UNICODE),
                            'shipment_weekdays_config' => json_encode($shipmentWeekdays, JSON_UNESCAPED_UNICODE),
                            'delivery_diff' => $shipmentDate->format('Y-m-d H:i:s'),
                            'delivery_weekend' => $route['delivery_weekend'],
                            'pick_diff' => $shipmentDate->format('Y-m-d H:i:s'),
                            'pick_weekend' => $route['pick_weekend'],
                            'pick_tariff_min' => $route['pick_tariff_min'],
                            'pick_tariff_vol' => $route['pick_tariff_vol'],
                            'pick_tariff_pallete' => $route['pick_tariff_pallete'],
                            'pick_additional' => $route['pick_additional'],
                            'delivery_tariff_min' => $route['delivery_tariff_min'],
                            'delivery_tariff_vol' => $route['delivery_tariff_vol'],
                            'delivery_tariff_pallete' => $route['delivery_tariff_pallete'],
                        ];
                    }
                }

                $current->addDay();
            }

            foreach (array_chunk($rows, 100) as $chunk) {
                SheetData::insert($chunk);
            }

            $totalRows += count($rows);
            $this->command->info("Route: {$route['distributor']} → {$route['distributor_center']}: " . count($rows) . ' rows');
        }

        $this->command->info('Total records: ' . $totalRows);
    }

    /**
     * Find shipment date: latest shipment weekday on or before (deliveryDate - minTransitDays).
     */
    private function resolveShipmentWithTransit(Carbon $deliveryDate, array $shipmentWeekdays, int $minTransitDays): ?Carbon
    {
        $candidate = $deliveryDate->copy()->subDays($minTransitDays);

        for ($attempt = 0; $attempt < 7; $attempt++) {
            if (in_array($candidate->dayOfWeek, $shipmentWeekdays, true)) {
                return $candidate;
            }
            $candidate->subDay();
        }

        return null;
    }

    private function getRoutes(): array
    {
        return [
            // === WILDBERRIES ===
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Тула (Алексин)',
                'distributor_address' => 'Тульская обл., г.о. Алексин, территория ВБ Алексин, 1',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 910.0,
                'delivery_tariff_vol' => 7100.0,
                'delivery_tariff_pallete' => 7100.0,
                'delivery_weekdays' => [1, 2, 3, 4, 5, 6, 0],
                'shipment_weekdays' => [2, 4, 0],
                'min_transit_days' => 3,
                'date_from' => '2026-02-04',
                'date_to' => '2026-03-03',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Подольск',
                'distributor_address' => 'Поливановская ул., 9, стр. 5, Подольск',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 850.0,
                'delivery_tariff_vol' => 6500.0,
                'delivery_tariff_pallete' => 6500.0,
                'delivery_weekdays' => [1, 2, 3, 4, 5, 6, 0],
                'shipment_weekdays' => [2, 4, 0],
                'min_transit_days' => 3,
                'date_from' => '2026-02-04',
                'date_to' => '2026-03-03',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Коледино',
                'distributor_address' => 'Индустриальный парк Коледино, Троицкая улица, 20',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 850.0,
                'delivery_tariff_vol' => 6500.0,
                'delivery_tariff_pallete' => 6500.0,
                'delivery_weekdays' => [1, 2, 3, 4, 5, 6, 0],
                'shipment_weekdays' => [2, 4, 0],
                'min_transit_days' => 3,
                'date_from' => '2026-02-04',
                'date_to' => '2026-03-03',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Электросталь',
                'distributor_address' => 'Поселок Случайный, территория Массив 3,5',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 950.0,
                'delivery_tariff_vol' => 7500.0,
                'delivery_tariff_pallete' => 7500.0,
                'delivery_weekdays' => [1, 2, 3, 4, 5, 6, 0],
                'shipment_weekdays' => [2, 4, 0],
                'min_transit_days' => 3,
                'date_from' => '2026-02-04',
                'date_to' => '2026-03-03',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Рязань',
                'distributor_address' => 'Индустриальный промышленный парк Рязанский, Тюшевское сельское поселение, Рязанский р-н',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 970.0,
                'delivery_tariff_vol' => 7700.0,
                'delivery_tariff_pallete' => 7700.0,
                'delivery_weekdays' => [1, 2, 3, 4, 5, 6, 0],
                'shipment_weekdays' => [2, 4, 0],
                'min_transit_days' => 3,
                'date_from' => '2026-02-04',
                'date_to' => '2026-03-03',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Казань',
                'distributor_address' => 'Зеленодольск, промышленная площадка Зеленодольск, 20',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 910.0,
                'delivery_tariff_vol' => 7100.0,
                'delivery_tariff_pallete' => 7100.0,
                'delivery_weekdays' => [1, 2, 3, 4, 5, 6, 0],
                'shipment_weekdays' => [2, 4, 0],
                'min_transit_days' => 4,
                'date_from' => '2026-02-05',
                'date_to' => '2026-03-04',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Новосемейкино',
                'distributor_address' => 'Индустриальный парк Новосемейкино, городское поселение Новосемейкино, Красноярский р-н, Самарская обл.',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 1020.0,
                'delivery_tariff_vol' => 8200.0,
                'delivery_tariff_pallete' => 8200.0,
                'delivery_weekdays' => [1, 2, 3, 4, 5, 6, 0],
                'shipment_weekdays' => [2, 4, 0],
                'min_transit_days' => 4,
                'date_from' => '2026-02-05',
                'date_to' => '2026-03-04',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Тамбов (Котовск)',
                'distributor_address' => 'Тамбовская обл., муниципальное образование г. Котовск, р-н индустриальный парк Котовск, 3/8',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 970.0,
                'delivery_tariff_vol' => 7700.0,
                'delivery_tariff_pallete' => 7700.0,
                'delivery_weekdays' => [1, 2, 3, 4, 5, 6],
                'shipment_weekdays' => [2, 4, 0],
                'min_transit_days' => 3,
                'date_from' => '2026-02-04',
                'date_to' => '2026-03-03',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Краснодар',
                'distributor_address' => 'Краснодар, ул. Тихорецкая, 40с1',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 700.0,
                'delivery_tariff_vol' => 5000.0,
                'delivery_tariff_pallete' => 5000.0,
                'delivery_weekdays' => [2, 3, 4, 5, 6, 0],
                'shipment_weekdays' => [2, 4, 0],
                'min_transit_days' => 2,
                'date_from' => '2026-02-03',
                'date_to' => '2026-03-01',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Невинномысск',
                'distributor_address' => 'Невинномысск, ул. Тимирязева 16',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 860.0,
                'delivery_tariff_vol' => 6600.0,
                'delivery_tariff_pallete' => 6600.0,
                'delivery_weekdays' => [2, 3, 4, 5, 6, 0],
                'shipment_weekdays' => [2, 4, 0],
                'min_transit_days' => 2,
                'date_from' => '2026-02-03',
                'date_to' => '2026-03-01',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Волгоград',
                'distributor_address' => 'Волгоград, Ангарская 149',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 1020.0,
                'delivery_tariff_vol' => 8200.0,
                'delivery_tariff_pallete' => 8200.0,
                'delivery_weekdays' => [3, 4],
                'shipment_weekdays' => [0],
                'min_transit_days' => 3,
                'date_from' => '2026-02-04',
                'date_to' => '2026-02-26',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Екатеринбург - Перспективный 14',
                'distributor_address' => 'Екатеринбург - Перспективный 14',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 1700.0,
                'delivery_tariff_vol' => 15000.0,
                'delivery_tariff_pallete' => 15000.0,
                'delivery_weekdays' => [2, 3],
                'shipment_weekdays' => [2],
                'min_transit_days' => 7,
                'date_from' => '2026-02-10',
                'date_to' => '2026-03-04',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Екатеринбург - Испытателей 14Г',
                'distributor_address' => 'Екатеринбург, ул. Испытателей, 14Г',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 1700.0,
                'delivery_tariff_vol' => 15000.0,
                'delivery_tariff_pallete' => 15000.0,
                'delivery_weekdays' => [2, 3],
                'shipment_weekdays' => [2],
                'min_transit_days' => 7,
                'date_from' => '2026-02-10',
                'date_to' => '2026-03-04',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Санкт-Петербург (Шушары)',
                'distributor_address' => 'Санкт-Петербург, Пушкинский район, посёлок Шушары, Московское шоссе, д. 153 к. 2',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 1190.0,
                'delivery_tariff_vol' => 9900.0,
                'delivery_tariff_pallete' => 9900.0,
                'delivery_weekdays' => [4, 5],
                'shipment_weekdays' => [4],
                'min_transit_days' => 7,
                'date_from' => '2026-02-12',
                'date_to' => '2026-03-06',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Санкт-Петербург (Уткина Заводь)',
                'distributor_address' => 'Ленинградская обл., Всеволожский р-н, Свердловское городское поселение, промзона Уткина Заводь 4, к.4',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 1190.0,
                'delivery_tariff_vol' => 9900.0,
                'delivery_tariff_pallete' => 9900.0,
                'delivery_weekdays' => [4, 5],
                'shipment_weekdays' => [4],
                'min_transit_days' => 7,
                'date_from' => '2026-02-12',
                'date_to' => '2026-03-06',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Симферополь (Молодежное)',
                'distributor_address' => 'пгт. Молодежное, Московское шоссе, 11',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 500.0,
                'delivery_tariff_vol' => 1500.0,
                'delivery_tariff_pallete' => 1500.0,
                'delivery_weekdays' => [1, 2, 3, 4, 5, 6, 0],
                'shipment_weekdays' => [1, 2, 3, 4, 5, 6, 0],
                'min_transit_days' => 1,
                'date_from' => '2026-02-05',
                'date_to' => '2026-03-03',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Владимир',
                'distributor_address' => 'Владимирская обл., Собинский муниципальный р-н, сельское поселение Воршинское',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 1020.0,
                'delivery_tariff_vol' => 8200.0,
                'delivery_tariff_pallete' => 8200.0,
                'delivery_weekdays' => [5, 6],
                'shipment_weekdays' => [0],
                'min_transit_days' => 5,
                'date_from' => '2026-02-06',
                'date_to' => '2026-02-28',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Воронеж',
                'distributor_address' => 'Воронежская обл., Новоусманский р-н, Отрадненское сельское поселение',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 970.0,
                'delivery_tariff_vol' => 7700.0,
                'delivery_tariff_pallete' => 7700.0,
                'delivery_weekdays' => [4, 5],
                'shipment_weekdays' => [0],
                'min_transit_days' => 4,
                'date_from' => '2026-02-05',
                'date_to' => '2026-02-27',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Сарапул',
                'distributor_address' => 'Удмуртская Республика, г. Сарапул, Ижевский тракт, д. 22',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 1190.0,
                'delivery_tariff_vol' => 9900.0,
                'delivery_tariff_pallete' => 9900.0,
                'delivery_weekdays' => [6, 0],
                'shipment_weekdays' => [0],
                'min_transit_days' => 6,
                'date_from' => '2026-02-07',
                'date_to' => '2026-03-01',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Пенза',
                'distributor_address' => 'Пензенский район, поселок Приовражный, ул. Новая, д. 100',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 1020.0,
                'delivery_tariff_vol' => 8200.0,
                'delivery_tariff_pallete' => 8200.0,
                'delivery_weekdays' => [4, 5],
                'shipment_weekdays' => [0],
                'min_transit_days' => 4,
                'date_from' => '2026-02-05',
                'date_to' => '2026-02-27',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Wildberries',
                'distributor_center' => 'Новосибирск',
                'distributor_address' => 'г. Новосибирск, ул. Петухова 71',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 11900.0,
                'delivery_tariff_vol' => 17000.0,
                'delivery_tariff_pallete' => 17000.0,
                'delivery_weekdays' => [4, 5],
                'shipment_weekdays' => [2],
                'min_transit_days' => 9,
                'date_from' => '2026-02-12',
                'date_to' => '2026-02-27',
            ],

            // === OZON ===
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Адыгея',
                'distributor_address' => 'Республика Адыгея, Теучежский район, хутор Кочкин, ул. Логистическая, д. 3, стр. 1',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 860.0,
                'delivery_tariff_vol' => 6600.0,
                'delivery_tariff_pallete' => 6600.0,
                'delivery_weekdays' => [4],
                'shipment_weekdays' => [0],
                'min_transit_days' => 4,
                'date_from' => '2026-02-12',
                'date_to' => '2026-02-19',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Невинномысск',
                'distributor_address' => 'Невинномысск, ул. Приозерная, зд. 25, стр. 1, к. 1',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 860.0,
                'delivery_tariff_vol' => 6600.0,
                'delivery_tariff_pallete' => 6600.0,
                'delivery_weekdays' => [1],
                'shipment_weekdays' => [4],
                'min_transit_days' => 4,
                'date_from' => '2026-02-09',
                'date_to' => '2026-02-23',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Пушкино-1',
                'distributor_address' => 'Московская обл., Пушкинский городской округ, г. Пушкино, Ярославское шоссе, д. 216.',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 700.0,
                'delivery_tariff_vol' => 5000.0,
                'delivery_tariff_pallete' => 5000.0,
                'delivery_weekdays' => [1],
                'shipment_weekdays' => [4],
                'min_transit_days' => 4,
                'date_from' => '2026-02-09',
                'date_to' => '2026-03-02',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Пушкино-1 (Кроссдок)',
                'distributor_address' => 'Московская обл., Пушкинский городской округ, г. Пушкино, Ярославское шоссе, д. 216.',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 700.0,
                'delivery_tariff_vol' => 5000.0,
                'delivery_tariff_pallete' => 5000.0,
                'delivery_weekdays' => [1],
                'shipment_weekdays' => [4],
                'min_transit_days' => 4,
                'date_from' => '2026-02-09',
                'date_to' => '2026-03-02',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Пушкино-2',
                'distributor_address' => 'Московская обл., г.о. Пушкинский, г. Пушкино, Ярославское шоссе, д. 218',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 700.0,
                'delivery_tariff_vol' => 5000.0,
                'delivery_tariff_pallete' => 5000.0,
                'delivery_weekdays' => [1],
                'shipment_weekdays' => [4],
                'min_transit_days' => 4,
                'date_from' => '2026-02-09',
                'date_to' => '2026-03-02',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Пушкино-2 (Кроссдок)',
                'distributor_address' => 'Московская обл., г.о. Пушкинский, г. Пушкино, Ярославское шоссе, д. 218',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 700.0,
                'delivery_tariff_vol' => 5000.0,
                'delivery_tariff_pallete' => 5000.0,
                'delivery_weekdays' => [1],
                'shipment_weekdays' => [4],
                'min_transit_days' => 4,
                'date_from' => '2026-02-09',
                'date_to' => '2026-03-02',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Хоругвино',
                'distributor_address' => 'Московская обл., Солнечногорский р-н, с. п. Пешковское, дер. Хоругвино, стр. 32/2',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 1020.0,
                'delivery_tariff_vol' => 8200.0,
                'delivery_tariff_pallete' => 8200.0,
                'delivery_weekdays' => [4],
                'shipment_weekdays' => [4],
                'min_transit_days' => 7,
                'date_from' => '2026-02-12',
                'date_to' => '2026-03-05',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Хоругвино (Кроссдок)',
                'distributor_address' => 'Московская обл., Солнечногорский р-н, с. п. Пешковское, дер. Хоругвино, стр. 32/2',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 1020.0,
                'delivery_tariff_vol' => 8200.0,
                'delivery_tariff_pallete' => 8200.0,
                'delivery_weekdays' => [4],
                'shipment_weekdays' => [4],
                'min_transit_days' => 7,
                'date_from' => '2026-02-12',
                'date_to' => '2026-03-05',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Софьино',
                'distributor_address' => 'Московская обл., Раменский городской округ, территория Логистический технопарк Софьино, 2/1',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 910.0,
                'delivery_tariff_vol' => 7100.0,
                'delivery_tariff_pallete' => 7100.0,
                'delivery_weekdays' => [4],
                'shipment_weekdays' => [4],
                'min_transit_days' => 7,
                'date_from' => '2026-02-12',
                'date_to' => '2026-03-05',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Жуковский',
                'distributor_address' => 'Московская обл., г. Жуковский, район Замоскворечье, д. 457, стр. 5',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 910.0,
                'delivery_tariff_vol' => 7100.0,
                'delivery_tariff_pallete' => 7100.0,
                'delivery_weekdays' => [4],
                'shipment_weekdays' => [4],
                'min_transit_days' => 7,
                'date_from' => '2026-02-12',
                'date_to' => '2026-03-05',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Казань',
                'distributor_address' => 'Республика Татарстан, г. Зеленодольск, промышленный парк Зеленодольск, зд. 19',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 910.0,
                'delivery_tariff_vol' => 7100.0,
                'delivery_tariff_pallete' => 7100.0,
                'delivery_weekdays' => [2],
                'shipment_weekdays' => [4],
                'min_transit_days' => 5,
                'date_from' => '2026-02-10',
                'date_to' => '2026-03-03',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Казань (Кроссдок)',
                'distributor_address' => 'Республика Татарстан, г. Зеленодольск, промышленный парк Зеленодольск, зд. 19',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 910.0,
                'delivery_tariff_vol' => 7100.0,
                'delivery_tariff_pallete' => 7100.0,
                'delivery_weekdays' => [2],
                'shipment_weekdays' => [4],
                'min_transit_days' => 5,
                'date_from' => '2026-02-10',
                'date_to' => '2026-03-03',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Санкт-Петербург (Шушары)',
                'distributor_address' => 'поселок Шушары, Московское шоссе, 143, с. 1',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 1190.0,
                'delivery_tariff_vol' => 9900.0,
                'delivery_tariff_pallete' => 9900.0,
                'delivery_weekdays' => [4],
                'shipment_weekdays' => [4],
                'min_transit_days' => 7,
                'date_from' => '2026-02-12',
                'date_to' => '2026-03-05',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Санкт-Петербург (Бугры)',
                'distributor_address' => 'Ленинградская область, Всеволожский район, с.п. Бугровское, тер. Бугры Массив, ул. Шоссейная, зд. 50, к. 1',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 1190.0,
                'delivery_tariff_vol' => 9900.0,
                'delivery_tariff_pallete' => 9900.0,
                'delivery_weekdays' => [4],
                'shipment_weekdays' => [4],
                'min_transit_days' => 7,
                'date_from' => '2026-02-12',
                'date_to' => '2026-03-05',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Санкт-Петербург (Петро-Славянка)',
                'distributor_address' => 'п. Петро-Славянка, ул. Софийская, д. 118, к. 4, стр. 1',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 1190.0,
                'delivery_tariff_vol' => 9900.0,
                'delivery_tariff_pallete' => 9900.0,
                'delivery_weekdays' => [4],
                'shipment_weekdays' => [4],
                'min_transit_days' => 7,
                'date_from' => '2026-02-12',
                'date_to' => '2026-03-05',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Санкт-Петербург (Колпино)',
                'distributor_address' => 'г. Санкт-Петербург, п. Шушары, Колпинское шоссе, д. 135, к.2, стр.1',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 1190.0,
                'delivery_tariff_vol' => 9900.0,
                'delivery_tariff_pallete' => 9900.0,
                'delivery_weekdays' => [4],
                'shipment_weekdays' => [4],
                'min_transit_days' => 7,
                'date_from' => '2026-02-12',
                'date_to' => '2026-03-05',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Екатеринбург',
                'distributor_address' => 'г. Екатеринбург, территория Логопарк Кольцовский, стр. 15',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 7500.0,
                'delivery_tariff_vol' => 15000.0,
                'delivery_tariff_pallete' => 15000.0,
                'delivery_weekdays' => [4],
                'shipment_weekdays' => [4],
                'min_transit_days' => 7,
                'date_from' => '2026-02-12',
                'date_to' => '2026-02-26',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Ногинск',
                'distributor_address' => 'Московская область, Богородский городской округ, рабочий поселок Обухово, территория Обухово-Парк, дом 2, строение 1',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 1020.0,
                'delivery_tariff_vol' => 8200.0,
                'delivery_tariff_pallete' => 8200.0,
                'delivery_weekdays' => [5],
                'shipment_weekdays' => [4],
                'min_transit_days' => 8,
                'date_from' => '2026-02-13',
                'date_to' => '2026-03-06',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Петровское',
                'distributor_address' => 'Московская обл, г. Истра, с. Петровское, территория МПСК Ориентир-Запад, зд. 1А',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 1020.0,
                'delivery_tariff_vol' => 8200.0,
                'delivery_tariff_pallete' => 8200.0,
                'delivery_weekdays' => [4],
                'shipment_weekdays' => [4],
                'min_transit_days' => 7,
                'date_from' => '2026-02-12',
                'date_to' => '2026-03-05',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Гривно',
                'distributor_address' => 'Московская обл., городской округ Подольск, д. Гривно, территория промышленного парка Гривно, д. 1, к. 13',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 700.0,
                'delivery_tariff_vol' => 5000.0,
                'delivery_tariff_pallete' => 5000.0,
                'delivery_weekdays' => [1, 4],
                'shipment_weekdays' => [4, 0],
                'min_transit_days' => 4,
                'date_from' => '2026-02-05',
                'date_to' => '2026-02-26',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Гривно (Кроссдок)',
                'distributor_address' => 'Московская обл., городской округ Подольск, д. Гривно, территория промышленного парка Гривно, д. 1, к. 13',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 700.0,
                'delivery_tariff_vol' => 5000.0,
                'delivery_tariff_pallete' => 5000.0,
                'delivery_weekdays' => [1, 4],
                'shipment_weekdays' => [4, 0],
                'min_transit_days' => 4,
                'date_from' => '2026-02-05',
                'date_to' => '2026-02-26',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Ростов-на-Дону',
                'distributor_address' => 'г. Ростов-на-Дону, Аксайский р-н, х. Ленина, ул. Логопарк 5',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 700.0,
                'delivery_tariff_vol' => 5000.0,
                'delivery_tariff_pallete' => 5000.0,
                'delivery_weekdays' => [2, 4, 5],
                'shipment_weekdays' => [2, 4, 0],
                'min_transit_days' => 1,
                'date_from' => '2026-02-03',
                'date_to' => '2026-02-27',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Ozon',
                'distributor_center' => 'Ростов-на-Дону (Кроссдок)',
                'distributor_address' => 'г. Ростов-на-Дону, Аксайский р-н, х. Ленина, ул. Логопарк 5',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 700.0,
                'delivery_tariff_vol' => 5000.0,
                'delivery_tariff_pallete' => 5000.0,
                'delivery_weekdays' => [2, 4, 5],
                'shipment_weekdays' => [2, 4, 0],
                'min_transit_days' => 1,
                'date_from' => '2026-02-03',
                'date_to' => '2026-02-27',
            ],

            // === ЯНДЕКС.МАРКЕТ ===
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Яндекс.Маркет',
                'distributor_center' => 'Софьино',
                'distributor_address' => 'Московская область, Раменский городской округ, логистический технопарк Софьино, стр. 3/1',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 910.0,
                'delivery_tariff_vol' => 7100.0,
                'delivery_tariff_pallete' => 7100.0,
                'delivery_weekdays' => [4],
                'shipment_weekdays' => [4],
                'min_transit_days' => 7,
                'date_from' => '2026-02-12',
                'date_to' => '2026-03-05',
            ],
            [
                'wh' => 'Склад Симферополь',
                'wh_address' => 'Респ. Крым, г. Симферополь, ул. Луговая, 6В',
                'map' => null,
                'distributor' => 'Яндекс.Маркет',
                'distributor_center' => 'Ростов-на-Дону',
                'distributor_address' => 'Ростовская область, Аксайский район, хутор Ленина, ул. Логопарк, д. 5',
                'delivery_weekend' => 0,
                'pick_weekend' => '0',
                'pick_tariff_min' => 0.0,
                'pick_tariff_vol' => 0.0,
                'pick_tariff_pallete' => 0.0,
                'pick_additional' => '0.0',
                'delivery_tariff_min' => 700.0,
                'delivery_tariff_vol' => 5000.0,
                'delivery_tariff_pallete' => 5000.0,
                'delivery_weekdays' => [2, 4, 5],
                'shipment_weekdays' => [2, 4, 0],
                'min_transit_days' => 1,
                'date_from' => '2026-02-03',
                'date_to' => '2026-02-27',
            ],
        ];
    }
}
